# Generated by Django 4.0.1 on 2022-02-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_eduction_plan_round_apply_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eduction',
            options={'verbose_name': 'การศึกษา', 'verbose_name_plural': 'ข้อมูลการศึกษา'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'แผนการเรียน', 'verbose_name_plural': 'ข้อมูลแผนการเรียน'},
        ),
        migrations.AlterModelOptions(
            name='round_apply',
            options={'verbose_name': 'รอบที่สมัคร', 'verbose_name_plural': 'ข้อมูลรอบบสมัคร'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'โรงเรียน', 'verbose_name_plural': 'ข้อมูลโรงเรียน'},
        ),
        migrations.AlterModelTable(
            name='eduction',
            table='Eduction',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='round_apply',
            table='Round_apply',
        ),
        migrations.AlterModelTable(
            name='school',
            table='School',
        ),
    ]
