# Generated by Django 4.0.1 on 2022-02-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='Plan',
        ),
    ]
