# Generated by Django 4.0.1 on 2022-02-01 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_school_size_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.plan'),
        ),
        migrations.AlterField(
            model_name='student',
            name='round_apply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.round_apply'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='short',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
