# Generated by Django 4.1.2 on 2022-11-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_alter_student_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ex1",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex10",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex11",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex12",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex13",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex14",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex15",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex16",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex17",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex18",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex19",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex2",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex20",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex3",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex4",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex5",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex6",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex7",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex8",
            field=models.IntegerField(
                choices=[
                    (0, "เห็นด้วยอย่างยิ่ง"),
                    (1, "เห็นด้วย"),
                    (2, "ไม่เห็นด้วย"),
                    (3, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ex9",
            field=models.IntegerField(
                choices=[
                    (3, "เห็นด้วยอย่างยิ่ง"),
                    (2, "เห็นด้วย"),
                    (1, "ไม่เห็นด้วย"),
                    (0, "ไม่เห็นด้วยอย่างยิ่ง"),
                ]
            ),
        ),
    ]
