# Generated by Django 4.1.3 on 2022-11-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_ex1_alter_student_ex10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='round_apply',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
