# Generated by Django 4.1.3 on 2022-11-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_rename_grade_student_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='round_apply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.round_apply'),
        ),
    ]
