# Generated by Django 4.1.3 on 2022-12-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.plan'),
        ),
        migrations.AlterField(
            model_name='student',
            name='round_apply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.round_apply'),
        ),
    ]
