# Generated by Django 4.1.3 on 2022-12-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_student_plan_alter_student_round_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='school',
            name='size_school',
            field=models.CharField(choices=[('โรงเรียนขนาดเล็ก', 'โรงเรียนขนาดเล็ก'), ('โรงเรียนขนาดกลาง', 'โรงเรียนขนาดกลาง'), ('โรงเรียนขนาดใหญ่', 'โรงเรียนขนาดใหญ่')], max_length=255),
        ),
    ]
