# Generated by Django 4.1.3 on 2022-12-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_rename_plan_name_plan_name_alter_school_size_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='round_apply',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
