# Generated by Django 4.1.3 on 2022-12-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_delete_eduction_delete_plan_delete_round_apply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='round_apply',
            field=models.CharField(choices=[('portfolio', 'portfolio'), ('รับตรงรอบที่ 2', 'รับตรงรอบที่ 2'), ('รับตรงรอบที่ 1', 'รับตรงรอบที่ 1'), ('โควต้า', 'โควต้า'), ('รับตรงอิสระ', 'รับตรงอิสระ'), ('นักศึกแลกเปลี่ยน', 'นักศึกแลกเปลี่ยน'), ('รับตรง(เพิ่มเติม)', 'รับตรง(เพิ่มเติม)')], max_length=255, null=True),
        ),
    ]
