# Generated by Django 4.1.3 on 2022-12-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_alter_student_round_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_student',
            field=models.CharField(choices=[('รุ่น 61', 'รุ่น 61'), ('รุ่น 62', 'รุ่น 62'), ('รุ่น 63', 'รุ่น 63'), ('รุ่น 64', 'รุ่น 64'), ('รุ่น 65', 'รุ่น 65'), ('รุ่น 66', 'รุ่น 66'), ('รุ่น 67', 'รุ่น 67'), ('รุ่น 68', 'รุ่น 68'), ('รุ่น 69', 'รุ่น 69'), ('รุ่น 70', 'รุ่น 70'), ('รุ่น 71', 'รุ่น 71'), ('รุ่น 72', 'รุ่น 72')], max_length=155, null=True),
        ),
    ]
