# Generated by Django 4.1.3 on 2023-01-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family_income_per_month',
            field=models.CharField(choices=[('ไม่เกิน5,000บาท', 'ไม่เกิน5,000บาท'), ('5,001–10,000บาท', '5,001–10,000บาท'), ('10,001-15,000บาท', '10,001-15,000บาท'), ('15,001-20,000 บาท', '15,001-20,000 บาท'), ('25,001บาทขึ้นไป', '25,001บาทขึ้นไป')], max_length=255, null=True),
        ),
    ]
