# Generated by Django 4.0.1 on 2022-02-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_plan_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='size_school',
            field=models.CharField(choices=[('โรงเรียนขนาดเล็ก', 'โรงเรียนขนาดเล็ก'), ('โรงเรียนขนาดกลาง', 'โรงเรียนขนาดกลาง'), ('โรงเรียนขนาดใหญ่', 'โรงเรียนขนาดใหญ่'), ('โรงเรียนขนาดใหญ่พิเศษ', 'โรงเรียนขนาดใหญ่พิเศษ')], max_length=255),
        ),
    ]
