# Generated by Django 4.1.2 on 2022-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_alter_student_plan_alter_student_round_apply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
