# Generated by Django 4.1.3 on 2022-11-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_student_plan_alter_student_round_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='GPA',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sophomore_student',
            new_name='class_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ComputerRelatedtraining',
            new_name='skillcomputer',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='family_status',
            new_name='status_family',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ComputerSkillsCompetition',
            new_name='traincomputer',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='learnProgramming',
            new_name='trainprogram',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Known_from_any_channel',
            new_name='want_to_develop',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='improve_skills',
            new_name='which_channel_do_you_know',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='programmingTraining',
            new_name='write_program',
        ),
        migrations.AddField(
            model_name='student',
            name='GPA_BRU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
