# Generated by Django 4.1.3 on 2022-11-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_round_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_student',
            field=models.CharField(choices=[('ชั้นปีที่ 1', 'ชั้นปีที่ 1'), ('ชั้นปีที่ 2', 'ชั้นปีที่ 2'), ('ชั้นปีที่ 3', 'ชั้นปีที่ 3'), ('ชั้นปีที่ 4', 'ชั้นปีที่ 4'), ('ชั้นปีที่ 5', 'ชั้นปีที่ 5'), ('ชั้นปีที่ 6', 'ชั้นปีที่ 6'), ('ชั้นปีที่ 7', 'ชั้นปีที่ 7'), ('ชั้นปีที่ 8', 'ชั้นปีที่ 8')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='round_apply',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
