# Generated by Django 4.1.3 on 2022-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_student_class_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_size',
            field=models.CharField(choices=[('โรงเรียนขนาดเล็ก', 'โรงเรียนขนาดเล็ก'), ('โรงเรียนขนาดกลาง', 'โรงเรียนขนาดกลาง'), ('โรงเรียนขนาดใหญ่', 'โรงเรียนขนาดใหญ่')], max_length=255, null=True),
        ),
    ]
