# Generated by Django 4.1.3 on 2022-12-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_student_plan_alter_student_round_apply_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eduction',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Round_apply',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RemoveField(
            model_name='student',
            name='GPA_BRU',
        ),
    ]
