# Generated by Django 4.1.3 on 2022-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_alter_student_class_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_size',
            field=models.CharField(choices=[('รร.ขนาดเล็ก', 'รร.ขนาดเล็ก'), ('รร.ขนาดกลาง', 'รร.ขนาดกลาง'), ('รร.ขนาดใหญ่', 'รร.ขนาดใหญ่')], max_length=255, null=True),
        ),
    ]
